return{}
--return {
--    "mason-org/mason-lspconfig.nvim",
--    opts = {
--        ensure_installed = {
--            "lua_ls",
--            "pyright",
--            --"ast_grep"
--        },
--    },
--    dependencies = {
--        {"mason-org/mason.nvim", opts = {} },
--         "neovim/nvim-lspconfig",
--    },
--}
